"""campuses


This work made by Anfinogentov Nikita

Revision ID: 561e08574c47
Revises: 
Create Date: 2026-10-06 17:16:00.681035
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561e08574c47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('university_name', sa.String(length=160), nullable=False),
    sa.Column('requester_email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_requests'))
    )
    op.create_index(op.f('ix_domain_requests_domain'), 'domain_requests', ['domain'], unique=False)
    op.create_table('email_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('campus_label', sa.String(length=80), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_domains')),
    sa.UniqueConstraint('domain', name=op.f('uq_email_domains_domain'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_domains')
    op.drop_index(op.f('ix_domain_requests_domain'), table_name='domain_requests')
    op.drop_table('domain_requests')
    # ### end Alembic commands ###
