"""events

This work made by Anfinogentov Nikita

Revision ID: 8f96d7043f38
Revises: 90efe7d47ba4
Create Date: 2026-10-06 17:25:55.747764
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f96d7043f38'
down_revision = '90efe7d47ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('idea_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description_md', sa.Text(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_text', sa.String(length=200), nullable=True),
    sa.Column('online_url', sa.String(length=500), nullable=True),
    sa.Column('campus_label', sa.String(length=80), nullable=True),
    sa.Column('going_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_events_created_by_users')),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('fk_events_idea_id_ideas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('idea_id', name=op.f('uq_events_idea_id'))
    )
    op.create_index(op.f('ix_events_ends_at'), 'events', ['ends_at'], unique=False)
    op.create_index(op.f('ix_events_starts_at'), 'events', ['starts_at'], unique=False)
    op.create_table('event_rsvps',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_rsvps_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_event_rsvps_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'user_id', name=op.f('pk_event_rsvps'))
    )
    op.create_index(op.f('ix_event_rsvps_user_id'), 'event_rsvps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_rsvps_user_id'), table_name='event_rsvps')
    op.drop_table('event_rsvps')
    op.drop_index(op.f('ix_events_starts_at'), table_name='events')
    op.drop_index(op.f('ix_events_ends_at'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
