"""ideas

This work made by Anfinogentov Nikita

Revision ID: 90efe7d47ba4
Revises: a98dd92d433b
Create Date: 2026-10-06 17:22:30.488095
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90efe7d47ba4'
down_revision = 'a98dd92d433b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ideas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.String(length=280), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('campus_label', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('team_size', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('review_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('team_formed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_ideas_author_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ideas'))
    )
    op.create_index(op.f('ix_ideas_author_id'), 'ideas', ['author_id'], unique=False)
    op.create_index(op.f('ix_ideas_category'), 'ideas', ['category'], unique=False)
    op.create_index(op.f('ix_ideas_created_at'), 'ideas', ['created_at'], unique=False)
    op.create_index(op.f('ix_ideas_status'), 'ideas', ['status'], unique=False)
    op.create_table('idea_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Uuid(), nullable=False),
    sa.Column('reporter_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('fk_idea_reports_idea_id_ideas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_idea_reports_reporter_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idea_reports')),
    sa.UniqueConstraint('idea_id', 'reporter_id', name='uq_idea_reports_idea_reporter')
    )
    op.create_index(op.f('ix_idea_reports_idea_id'), 'idea_reports', ['idea_id'], unique=False)
    op.create_table('idea_team_members',
    sa.Column('idea_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('fk_idea_team_members_idea_id_ideas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_idea_team_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idea_id', 'user_id', name=op.f('pk_idea_team_members'))
    )
    op.create_index(op.f('ix_idea_team_members_user_id'), 'idea_team_members', ['user_id'], unique=False)
    op.create_table('idea_votes',
    sa.Column('idea_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('fk_idea_votes_idea_id_ideas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_idea_votes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idea_id', 'user_id', name=op.f('pk_idea_votes'))
    )
    op.create_index(op.f('ix_idea_votes_created_at'), 'idea_votes', ['created_at'], unique=False)
    op.create_index(op.f('ix_idea_votes_user_id'), 'idea_votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idea_votes_user_id'), table_name='idea_votes')
    op.drop_index(op.f('ix_idea_votes_created_at'), table_name='idea_votes')
    op.drop_table('idea_votes')
    op.drop_index(op.f('ix_idea_team_members_user_id'), table_name='idea_team_members')
    op.drop_table('idea_team_members')
    op.drop_index(op.f('ix_idea_reports_idea_id'), table_name='idea_reports')
    op.drop_table('idea_reports')
    op.drop_index(op.f('ix_ideas_status'), table_name='ideas')
    op.drop_index(op.f('ix_ideas_created_at'), table_name='ideas')
    op.drop_index(op.f('ix_ideas_category'), table_name='ideas')
    op.drop_index(op.f('ix_ideas_author_id'), table_name='ideas')
    op.drop_table('ideas')
    # ### end Alembic commands ###
