"""outbox and mail queue


This work made by Anfinogentov Nikita

Revision ID: b8af4949e74b
Revises: 561e08574c47
Create Date: 2026-10-06 17:16:40.535590
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8af4949e74b'
down_revision = '561e08574c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mail_queue'))
    )
    op.create_index(op.f('ix_mail_queue_sent_at'), 'mail_queue', ['sent_at'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('idea_id', sa.Uuid(), nullable=True),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('campus_label', sa.String(length=80), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox')),
    sa.UniqueConstraint('uid', name=op.f('uq_outbox_uid'))
    )
    op.create_index(op.f('ix_outbox_shipped_at'), 'outbox', ['shipped_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_shipped_at'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_mail_queue_sent_at'), table_name='mail_queue')
    op.drop_table('mail_queue')
    # ### end Alembic commands ###
